language: php

php:
    - 7.1
    - 7.2

install:
    - composer update $COMPOSER_FLAGS

script:
    # dry run
    - vendor/bin/rector process src/Controller --dry-run

    # apply
    - vendor/bin/rector process src/Form

    # with style option test
    - vendor/bin/rector process src/Form --with-style

    # yaml
    - vendor/bin/rector process config --level symfony30 --dry-run

notifications:
    email: false
